POST http://localhost:8010/register/
Content-Type: application/json

{
    "userName": "user1",
    "password": "pass"
}
###

POST http://localhost:8010/login/
Content-Type: application/json

{
    "userName": "user1",
    "password": "pass"
}
###